export default [
	{
		id: "1",
		title: "Студия, 27 м²",
		rooms: 1,
		size: 27,
		project: "«Ёлки-Park»",
		capacity: "12",
		lowestPrice: 1800000,
		highestPrice: 4200000,
		toilets: 1,
		wardrobe: "false",
		bigLoggia: "true",
		studio: "true",
		laundry: "false",
		release: 2023,
		view: "Панорамный",
		ceiling: 2.7,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "2",
		title: "Студия, 27 м²",
		rooms: 1,
		size: 27,
		project: "«ZNAK»",
		capacity: "12",
		lowestPrice: 1950000,
		highestPrice: 4100000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "false",
		studio: "true",
		laundry: "false",
		release: 2022,
		view: "Во двор",
		ceiling: 2.5,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "3",
		title: "Студия, 31 м²",
		rooms: 1,
		size: 31,
		project: "«Железно на Володарского»",
		capacity: "14",
		lowestPrice: 2110000,
		highestPrice: 4450000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "true",
		laundry: "false",
		release: 2022,
		view: "Во двор",
		ceiling: 2.5,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "4",
		title: "Студия, 28 м²",
		rooms: 1,
		size: 28,
		project: "«Ёлки-Park»",
		capacity: "8",
		lowestPrice: 2000000,
		highestPrice: 4010000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "false",
		studio: "true",
		laundry: "false",
		release: 2024,
		view: "На город",
		ceiling: 2.7,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "5",
		title: "5 комнат, 107 м²",
		rooms: 5,
		size: 107,
		project: "«Ёлки-Park»",
		capacity: "3",
		lowestPrice: 3550000,
		highestPrice: 6990000,
		toilets: 3,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "false",
		release: 2023,
		view: "Панорамный",
		ceiling: 3.1,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "6",
		title: "3 комнаты, 68 м²",
		rooms: 3,
		size: 68,
		project: "«Железно на Володарского»",
		capacity: "5",
		lowestPrice: 3150000,
		highestPrice: 4695000,
		toilets: 2,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "true",
		release: 2023,
		view: "На парк",
		ceiling: 3.1,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "7",
		title: "2 комнаты, 44 м²",
		rooms: 2,
		size: 44,
		project: "«Железно на Володарского»",
		capacity: "5",
		lowestPrice: 4150000,
		highestPrice: 5695000,
		toilets: 2,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "true",
		release: 2022,
		view: "На парк",
		ceiling: 3.1,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "8",
		title: "1 комната, 34 м²",
		rooms: 1,
		size: 34,
		project: "«Васильки»",
		capacity: "5",
		lowestPrice: 3150000,
		highestPrice: 4695000,
		toilets: 2,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "true",
		release: 2023,
		view: "Во двор",
		ceiling: 3.1,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "9",
		title: "4 комнаты, 71 м²",
		rooms: 4,
		size: 68,
		project: "«Железно на Володарского»",
		capacity: "15",
		lowestPrice: 5150000,
		highestPrice: 8695000,
		toilets: 3,
		wardrobe: "false",
		bigLoggia: "false",
		studio: "false",
		laundry: "true",
		release: 2024,
		view: "На парк",
		ceiling: 2.7,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "10",
		title: "6 комнат, 121 м²",
		rooms: 6,
		size: 121,
		project: "«ZNAK»",
		capacity: "3",
		lowestPrice: 7550000,
		highestPrice: 9990000,
		toilets: 3,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "false",
		release: 2023,
		view: "Панорамный",
		ceiling: 3.1,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	},
	{
		id: "11",
		title: "4 комнатs, 92 м²",
		rooms: 4,
		size: 92,
		project: "«ZNAK»",
		capacity: "3",
		lowestPrice: 3450000,
		highestPrice: 7990000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "false",
		release: 2023,
		view: "Панорамный",
		ceiling: 2.7,
		image: "house-main",
		plan: "house-plan",
		filtered: true
	}
]