export default [
	{
		id: "1",
		title: "Студия, 27 м²",
		rooms: 1,
		size: 27,
		location: "Ёлки-Park",
		capacity: "12",
		lowestPrice: 1800000,
		highestPrice: 4200000,
		toilets: 1,
		wardrobe: "false",
		bigLoggia: "true",
		studio: "true",
		laundry: "false",
		release: 2023,
		view: "panoramic",
		celinig: 2.7,
		image: "house-main",
		plan: "house-plan"
	},
	{
		id: "2",
		title: "Студия, 27 м²",
		rooms: 1,
		size: 27,
		location: "ZNAK",
		capacity: "12",
		lowestPrice: 1950000,
		highestPrice: 4100000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "false",
		studio: "true",
		laundry: "false",
		release: 2022,
		view: "yard",
		celinig: 2.5,
		image: "house-main",
		plan: "house-plan"
	},
	{
		id: "3",
		title: "Студия, 31 м²",
		rooms: 1,
		size: 31,
		location: "«Железно на Володарского»",
		capacity: "14",
		lowestPrice: 2110000,
		highestPrice: 4450000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "true",
		laundry: "false",
		release: 2022,
		view: "yard",
		celinig: 2.5,
		image: "house-main",
		plan: "house-plan"
	},
	{
		id: "4",
		title: "Студия, 28 м²",
		rooms: 1,
		size: 28,
		location: "Ёлки-Park",
		capacity: "8",
		lowestPrice: 2000000,
		highestPrice: 4010000,
		toilets: 1,
		wardrobe: "true",
		bigLoggia: "false",
		studio: "true",
		laundry: "false",
		release: 2022,
		view: "city",
		celinig: 2.7,
		image: "house-main",
		plan: "house-plan"
	},
	{
		id: "5",
		title: "4+ комнаты, 107 м²",
		rooms: 5,
		size: 107,
		location: "Ёлки-Park",
		capacity: "3",
		lowestPrice: 3550000,
		highestPrice: 6990000,
		toilets: 3,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "false",
		release: 2023,
		view: "panoramic",
		celinig: 3.1,
		image: "house-main",
		plan: "house-plan"
	},
	{
		id: "6",
		title: "3 комнаты, 68 м²",
		rooms: 3,
		size: 68,
		location: "Железно на Володарского",
		capacity: "5",
		lowestPrice: 3150000,
		highestPrice: 4695000,
		toilets: 2,
		wardrobe: "true",
		bigLoggia: "true",
		studio: "false",
		laundry: "true",
		release: 2023,
		view: "park",
		celinig: 3.1,
		image: "house-main",
		plan: "house-plan"
	}
]